version: "3.1"

services:
  client:
    build:
      # Caminho do arquivo
      context: ./client
      # Nome do arquivo
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      # Setando a comunicacao entre os containers
      - webapp-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webapp-network

  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    ports:
      - 27011:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - webapp-network
    volumes:
      - ./data:/data/db

#  mongo-express:
#    image: mongo-express:0.54.0
#    restart: always
#    ports:
#      - "8080:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#      ME_CONFIG_MONGODB_SERVER: mongo-server
#      ME_CONFIG_MONGODB_PORT: 27017
#    depends_on:
#      - mongodb
#    volumes:
#      - ./data:/data/db

networks:
  webapp-network:
    driver: bridge