version: "2"
services:
  client:
    build:
      # Caminho do arquivo
      context: ./client
      # Nome do arquivo
      dockerfile: Dockerfile
    restart: always
    # Nome do container
    container_name: app_mygooddoctor_client_1
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      # Setando a comunicacao entre os containers
      - webapp-network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    container_name: app_mygooddoctor_api_1
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webapp-network
  mongodb:
    image: mongo:4.0
    restart: always
    container_name: app_mygooddoctor_db_1
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - webapp-network
networks:
  webapp-network:
    driver: bridge